fail_fast: false
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ --profile, black, --filter-files ]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types_or: [ python, pyi ]
      - id: mypy
        name: mypy
        language: system
        files: src
        types: [ python ]
        entry: mypy
        args: ["--ignore-missing-imports"]
      - id: pytest
        name: pytest
        files: tests/
        entry: pytest
        language: system
        pass_filenames: false
      - id: locks
        name: Update locks
        files: pyproject.toml
        entry: pipenv lock
        language: system
        pass_filenames: false
